USE [MIS_DEV]
GO
/****** Object:  StoredProcedure [dbo].[SP_REPORT_PL_KHOI_QT]    Script Date: 9/23/2025 11:53:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_REPORT_PL_KHOI_QT]
	--@FDATE DATE = NULL, --Tu ngay
	@TDATE DATE = '2025-07-27' --Den ngay
AS
BEGIN
	SET NOCOUNT ON

	--DECLARE @TDATE_TT DATE --Ngay cuoi thang truoc
	--SET @TDATE_TT = DATEADD(DAY, -DAY(@TDATE),@TDATE)

	--IF @FDATE IS NULL 
	--	SET @FDATE = FORMAT(@TDATE,'yyyy-01-01')

	DECLARE @STR_EXEC NVARCHAR(MAX) = ''

	DROP TABLE IF EXISTS #LIST_BRANCH

	SELECT DISTINCT 'VN0010' + BRANCH_CODE AS BRANCH_CODE, CAST(0 AS INT) AS INSERTED
	INTO #LIST_BRANCH
	FROM [MBV_MIS_DB ].[APPS].[MB_STAG_GL_ORS_PL] WHERE REPORT_DATE = @TDATE

	--delete from #LIST_BRANCH
	--where BRANCH_CODE <> 'vn0010001'
	------------------------------------------------------------------------------------------------------------------
	DROP TABLE IF EXISTS #FOMULA 

	SELECT *, CAST(0 AS INT) AS INSERTED 
	INTO #FOMULA
	FROM MIS_DEV.DBO.MAP_PL_QUAN_TRI_FOMULA
	------------------------------------------------------------------------------------------------------------------
	DROP TABLE IF EXISTS #DATA_PL 

	--HoangDM: So phat sinh tu FDate toi TDate
	SELECT 'VN0010' + BRANCH_CODE AS BRANCH_CODE, KPI_CODE, DIVISION_CODE, 
		SUM(AMOUNT) AS AMOUNT
	INTO #DATA_PL
	FROM [MBV_MIS_DB ].[APPS].[MB_STAG_GL_ORS_PL]
	WHERE REPORT_DATE = @TDATE 
	GROUP BY BRANCH_CODE, KPI_CODE, DIVISION_CODE
	
	UPDATE #DATA_PL
	SET DIVISION_CODE = 'TREASURY'
	WHERE DIVISION_CODE = 'TREA'

	UPDATE #DATA_PL
	SET DIVISION_CODE = 'KXD'
	WHERE DIVISION_CODE IN ('KHOI KD-KXD', N'KHÁC', 'KHOI_KD_KXD') OR DIVISION_CODE IS NULL 

	UPDATE #DATA_PL 
	SET DIVISION_CODE = 'NHS'
	WHERE DIVISION_CODE = 'COST CENTER' OR DIVISION_CODE ='?COST CENTER?'

	UPDATE #DATA_PL
	SET DIVISION_CODE = 'SMEs' 
	WHERE DIVISION_CODE IN ('SME','?SMEs?')

	CREATE NONCLUSTERED INDEX BRANCH_CODE ON #DATA_PL (BRANCH_CODE);
	CREATE NONCLUSTERED INDEX KPI_CODE ON #DATA_PL (KPI_CODE);
	------------------------------------------------------------------------------------------------------------------
	--TOI DATA:
	DROP TABLE IF EXISTS ##DATA_TOI

	--SELECT T.MA_CN AS BRANCH_CODE, T.KHOI AS DIVISION_CODE,
	--	SUM(T.THULAI_KH_A) AS THULAI_KH_A, SUM(CHILAI_FTP_B) AS CHILAI_FTP_B, SUM(T.CHI_DP_F) AS CHI_DP_F 
	--INTO ##DATA_TOI
	--FROM [MBV_MIS_DB ].[APPS].[REP_TOI_FINAL_MONTH_LK] T
	--	INNER JOIN MASTER_DATA.DBO.DIM_BAD_BOOK V on T.MAKH = V.T24_CUSTOMER_ID and [Phân loại] != 'No tiem an'
	--WHERE TRANSACTION_DATE = @TDATE_TT AND T.KHOI IN('INDIV','SME','CIB','FI')
	--GROUP BY T.MA_CN, T.KHOI	

	--HoangDM: Lay truc tiep Data TOI tu FTP 
	SET @STR_EXEC = N'
		SELECT TRIM(T.MA_CN) AS BRANCH_CODE, T.KHOI AS DIVISION_CODE,
				SUM(T.THULAI_KH_A) AS THULAI_KH_A, 
				SUM(T.CHILAI_FTP_B) AS CHILAI_FTP_B, 
				SUM(T.CHI_DP_F) AS CHI_DP_F 
		INTO ##DATA_TOI
		FROM OPENQUERY(ftp1_linked, 
			''SELECT MA_CN, KHOI, THULAI_KH_A, CHILAI_FTP_B, CHI_DP_F, MAKH 
				FROM APPS.REP_TOI_FINAL_TT
				WHERE TRANSACTION_DATE BETWEEN ''''2025-02-07'''' AND ''''' + CAST(@TDATE AS VARCHAR(10)) + N''''' 
				AND TRIM(KHOI) IN (''''INDIV'''',''''SME'''',''''CIB'''',''''FI'''')''
		) T
			INNER JOIN MASTER_DATA.DBO.DIM_BAD_BOOK V ON T.MAKH = V.T24_CUSTOMER_ID 
				AND V.[Phân loại] != ''No tiem an''
		GROUP BY TRIM(T.MA_CN), T.KHOI;
		'
	EXEC (@STR_EXEC)

	UPDATE ##DATA_TOI
	SET DIVISION_CODE = 'SMEs'
	WHERE DIVISION_CODE = 'SME'
	------------------------------------------------------------------------------------------------------------------
	--NIM DATA
	DROP TABLE IF EXISTS ##DATA_NIM
	--SELECT T1.CN AS BRANCH_CODE, T1.KHOI AS DIVISION_CODE,
	--	SUM(REAL_INTEREST_VND) AS REAL_INTEREST_VND, SUM(INTEREST_FTP_VND) AS INTEREST_FTP_VND
	--INTO ##DATA_NIM
	--FROM ftp1_linked..APPS.MB_AGG_NIM_M T1
	--	INNER JOIN MASTER_DATA.DBO.DIM_PVI_SBIC T2 ON T1.TAIKHOAN = T2.ARRANGEMENT_NBR AND T2.PVN_SBIC = 'PVN_SBIC'
	--WHERE KHOI IN ('INDIV','SME','CIB','FI') AND D_TYPE = 'DEPOSIT'
	--	AND TRANSACTION_DATE = @TDATE_TT 
	--GROUP BY T1.CN, T1.KHOI

	--HoangDM: Lay truc tiep Data NIM tu FTP 
	SET @STR_EXEC = '
		SELECT T1.CN AS BRANCH_CODE,  T1.KHOI AS DIVISION_CODE,
			   SUM(REAL_INTEREST_VND) AS REAL_INTEREST_VND, 
			   SUM(INTEREST_FTP_VND) AS INTEREST_FTP_VND
		INTO ##DATA_NIM
		FROM OPENQUERY(ftp1_linked, 
			''SELECT CN, KHOI, REAL_INTEREST_VND, INTEREST_FTP_VND, TAIKHOAN 
			  FROM APPS.MB_AGG_NIM_M 
			  WHERE D_TYPE = ''''DEPOSIT'''' 
				AND TRANSACTION_DATE BETWEEN ''''2025-02-07'''' AND ''''' + CAST(@TDATE AS varchar(10)) + '''''
				AND TRIM(KHOI) IN (''''INDIV'''',''''SME'''',''''CIB'''',''''FI'''')''
		) T1
			INNER JOIN MASTER_DATA.DBO.DIM_PVI_SBIC T2 ON T1.TAIKHOAN = T2.ARRANGEMENT_NBR 
				AND T2.PVN_SBIC = ''PVN_SBIC''
		GROUP BY T1.CN, T1.KHOI;
		'		
	EXEC (@STR_EXEC);

	UPDATE ##DATA_NIM
	SET DIVISION_CODE = 'SMEs'
	WHERE DIVISION_CODE = 'SME'
	------------------------------------------------------------------------------------------------------------------
	--V6 DATA
	DROP TABLE IF EXISTS #DATA_V6
	SELECT CNC1 AS BRANCH_CODE, 
		CASE WHEN LINE_GL = '704000' THEN 'SMEs'
			WHEN LINE_GL = '704100' THEN 'INDIV'
			WHEN LINE_GL = '703900' THEN 'CIB' END AS DIVISION_CODE,
		SUM(CUOIKY_CREDIT) AS CUOIKY_CREDIT ,
		SUM(CUOIKY_DEBIT) AS CUOIKY_DEBIT 
	INTO #DATA_V6
	FROM [MBV_MIS_DB ].APPS.MB_GL_V6_BALANCES
	WHERE TRANSACTION_DATE = @TDATE AND LINE_GL IN ('704000','704100','703900')
	GROUP BY CNC1, LINE_GL
	------------------------------------------------------------------------------------------------------------------
	DROP TABLE IF EXISTS #RAW_DATA

	CREATE TABLE #RAW_DATA
	(
		STT INT,
		ITEM_CODE VARCHAR(100),
		ITEM_NAME NVARCHAR(250),
		MA_SO VARCHAR(15),
		BRANCH_CODE VARCHAR(15),
		DIVISION_CODE VARCHAR(15),
		AMOUNT NUMERIC(38,4)
	)


	--HoangDM: import tay TOI truoc 7/2:
	DROP TABLE IF EXISTS #TEMP 
	CREATE TABLE #TEMP	 
	(
		BRANCH_CODE NVARCHAR(50),
		ITEM_CODE VARCHAR(50),
		ITEM_NAME NVARCHAR(250),
		MA_SO NVARCHAR(50),
		INDIV NUMERIC(30,0),
		FI NUMERIC(30,0),
		SMEs NUMERIC(30,0)

	)

	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010001', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -23063008932.2512 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010002', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -31.0301369863013 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010003', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 2298686215, -3833905889.4143 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010004', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -13201007.0755677 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010005', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010006', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010007', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010008', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010009', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010010', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010011', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -6005.10223561644 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010012', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010013', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010014', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010017', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010020', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -466.966575342465 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010028', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010029', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010030', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 224, -7349582.8650992 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010031', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -2403422927.26982 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010032', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010033', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010034', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010035', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, -12, -424.915616438356 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010036', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010037', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010051', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -82936047.0262904 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010052', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010053', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010054', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -142392264.542296 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010055', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010056', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -104071618.190434 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010057', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -21698.1943123287 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010058', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010059', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 9556, -1916651087.40273 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010060', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010061', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010062', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010063', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010064', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010065', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 10645, -9657815.65931505 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010066', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010067', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010068', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010069', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010070', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010071', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -53354.1204946336 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010072', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010073', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010074', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010075', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010076', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010077', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010078', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010079', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010080', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -681.086827397259 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010081', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -35764.7944876712 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010086', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -9225525175.32405 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010090', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010091', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -43282402.9117808 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010092', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010093', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -888.325347945205 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010095', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -250683.531654794 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010096', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010100', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010101', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 3600267557, -4827976714.11084 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010102', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010103', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 13407, -4712216601.40955 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010105', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -2530.16542465753 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010106', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -180.73802739726 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010107', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010108', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010109', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010110', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 1445, -24746429.9004497 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010111', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010112', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010113', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010114', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010115', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010116', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010117', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010120', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010141', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010142', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010143', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010144', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 1065, -3197.57587945205 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010146', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -1018.77248219178 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010154', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010155', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -243.078410958903 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010157', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010161', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010202', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -50.5168493150684 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010203', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -149.889304109588 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010204', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010205', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -31806680.9628931 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010208', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -123166866.83362 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010221', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010223', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -459.031780821918 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010231', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010232', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010233', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010252', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010666', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010001', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 24401518805.3507 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010002', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 443.596184520547 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010003', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -349633370.55, 2147651888.38504 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010004', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 13689349.8465745 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010005', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010006', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010007', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010008', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010009', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010010', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010011', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 15013.1405205479 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010012', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010013', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010014', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010017', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010020', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 1167.41095890411 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010028', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010029', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010030', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -660.39, 7578961.75510512 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010031', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -199.92, 2460894789.59258 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010032', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010033', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010034', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010035', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, -517.716438356166 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010036', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010037', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010051', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -31.3599999999999, 85338586.6565432 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010052', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010053', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010054', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -80.8000000000002, 147541473.954747 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010055', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010056', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 109681524.718669 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010057', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 54245.2433150684 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010058', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010059', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 121198.73, 1963497215.07429 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010060', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010061', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010062', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010063', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010064', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010065', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -29636.49, 9833130.65054137 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010066', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010067', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010068', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010069', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010070', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010071', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 134935.855473702 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010072', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010073', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010074', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010075', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010076', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010077', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010078', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010079', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010080', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 1703.16090410958 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010081', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 89411.586219178 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010086', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -50.4399999999998, 9549062745.4766 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010090', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010091', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 44760769.8995479 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010092', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010093', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 2220.95446575341 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010095', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 626707.001315068 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010096', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010100', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010101', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, -1436.67, 1293095423.97302 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010102', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010103', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 261912.22, 4852926857.17391 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010105', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 6325.38479452054 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010106', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 451.843698630137 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010107', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010108', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010109', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010110', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 66994.97, 25535826.7174054 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010111', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010112', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010113', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010114', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010115', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010116', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010117', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010120', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010141', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010142', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010143', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010144', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 18676, -32363.5849589041 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010146', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 2547.07367123287 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010154', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010155', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 607.693287671232 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010157', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010161', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010202', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 126.290753424657 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010203', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 374.721890410958 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010204', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010205', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 33280990.4094383 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010208', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 126202120.821577 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010221', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010223', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 1150.58767123288 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010231', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010232', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010233', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010252', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010666', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010001', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -1444548651, 0, -9984639486 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010002', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -67965924, 0, -119056821 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010003', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -28093128, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010004', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -3458598, 0, -429523628 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010005', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -43780438, 0, -2048943 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010006', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010007', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010008', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -5102023, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010009', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -4741979, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010010', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -67536279, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010011', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, -1461386823 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010012', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -33316062, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010013', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -6665685, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010014', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -20519016, 0, -58166433 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010017', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010020', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -101796970, 0, -58995807 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010028', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -1711242, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010029', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -920558, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010030', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -41385755, 0, -9066369 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010031', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -13949364, 0, -98909739 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010032', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -16266540, 0, -224067441 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010033', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -21187335, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010034', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -43345772, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010035', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -465781240, 0, -427796825 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010036', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010037', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010051', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -46597827, 0, -115817208 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010052', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -41642640, 0, -321179352 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010053', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -24472238, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010054', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -147499746, 0, -627438725 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010055', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -39511770, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010056', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -58425315, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010057', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -2446626, 0, -993713 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010058', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -12243577, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010059', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -34676394, 0, -12639276 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010060', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -23913660, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010061', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010062', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -22688584, 0, -2389218 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010063', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -19384950, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010064', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -37191961, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010065', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -15638544, 0, -15452697 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010066', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -438048, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010067', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -6205836, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010068', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -1109901, 0, -261646479 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010069', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010070', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -26917446, 0, -646086216 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010071', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -961116, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010072', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -5422169, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010073', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -22284093, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010074', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -1656915, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010075', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010076', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010077', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -5011890, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010078', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010079', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010080', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010081', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -28075363, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010086', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, -972048192 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010090', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -4490159, 0, -342840658 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010091', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -43466381, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010092', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010093', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010095', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -43214576, 0, -366347153 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010096', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010100', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010101', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -496679501, 0, -3260354058 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010102', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010103', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -8643765, 0, -74862918 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010105', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010106', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010107', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010108', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010109', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010110', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -24711696, 0, -449620665 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010111', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -75660, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010112', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010113', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010114', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -2426187, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010115', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -8285550, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010116', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010117', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010120', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010141', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -4893577, 0, -29880357 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010142', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010143', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010144', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -10122587, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010146', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -3522558, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010154', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -161945226, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010155', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -4223934, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010157', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -6964612, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010161', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -36202881, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010202', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -648726, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010203', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010204', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -73395621, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010205', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -201747, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010208', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -27825658, 0, -60583575 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010221', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -633009, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010223', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -6383325, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010231', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -55380, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010232', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010233', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010252', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -9803235, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010666', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010001', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -888784, 0, -128970640.725 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010002', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -17690720, 0, -2327852222 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010003', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -6580365, 0, 428992319 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010004', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -77177, 0, 348224205 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010005', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 305266926, 0, -2407056 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010006', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010007', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -28745, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010008', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -2102406, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010009', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1872066, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010010', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -2147303, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010011', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, -49505785 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010012', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1201778, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010013', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -243463, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010014', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -464607, 0, -46296 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010017', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010020', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -23510593, 0, -1789704 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010028', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -20433, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010029', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 38713775, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010030', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 105523717, 0, -118009 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010031', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -3205916, 0, -36087972.725 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010032', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -5890572, 0, -173223 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010033', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -16638409, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010034', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -422586, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010035', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -137490100, 0, 477302961.2 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010036', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010037', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010051', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -16296197, 0, -1116276 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010052', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1563087, 0, -216598 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010053', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -14378393, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010054', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -870642, 0, 169766084 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010055', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -3488716, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010056', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -268048, 0, 21119414698 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010057', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -21280, 0, -1253887.3 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010058', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -11173092, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010059', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -4108787, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010060', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -3781420, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010061', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010062', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -8854750, 0, 1891780139.6 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010063', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1303754, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010064', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 1230694, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010065', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1289398, 0, -17376399 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010066', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -6670, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010067', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 8961264, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010068', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -6637, 0, -722124 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010069', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010070', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 1115076709, 0, 327963401 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010071', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -8675, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010072', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 37878678, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010073', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -6279392, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010074', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -10475, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010075', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010076', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010077', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -173402, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010078', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010079', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010080', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010081', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -15982526, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010086', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, -183353391.25 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010090', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1406042, 0, 187236034 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010091', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -41835420, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010092', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010093', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010095', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -25643343, 0, 220697730 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010096', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010100', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010101', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -201746598, 0, 16161275993 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010102', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010103', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -98667, 0, -74247 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010105', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010106', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010107', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010108', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010109', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 1384294722, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010110', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -4149600, 0, -9544012 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010111', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010112', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010113', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010114', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -349889, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010115', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010116', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010117', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010120', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010141', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 19846, 0, -20205 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010142', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010143', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010144', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -1873089, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010146', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -45051, 0, 1894537145 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010154', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -52438793, 0, 236107585799 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010155', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -100930, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010157', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -206217, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010161', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -3628560, 0, 10273099157 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010202', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -2774, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010203', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010204', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -2567760, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010205', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010208', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 1325767, 0, -13248 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010221', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -924, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010223', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -29785, 0, 652483743 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010231', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010232', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 2472510, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010233', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010252', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, -1052082 
INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010666', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 

	DROP TABLE IF EXISTS #TEMP2
	SELECT *  
	INTO #TEMP2
	FROM MIS_DEV.DBO.MAP_PL_QUAN_TRI_FOMULA
	WHERE STT IN (5,8,18,21,57)

	;WITH CTE AS
	(
	SELECT T2.STT, T1.*
	FROM #TEMP T1
		LEFT JOIN #TEMP2 T2 ON T1.ITEM_CODE = T2.ITEM_CODE
		)
		insert into #RAW_DATA(STT,ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
		SELECT STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, GIA_TRI
		FROM CTE
		UNPIVOT (
			GIA_TRI FOR DIVISION_CODE IN (
				INDIV, SMEs, FI
			)
		) AS UNPVT;


	DECLARE @BRANCH_CODE VARCHAR(15)

	DECLARE @STT INT, @ITEM_CODE VARCHAR(50), @ITEM_NAME NVARCHAR(250), @MA_SO VARCHAR(15), @SOURCE_COL VARCHAR(250)
		, @SOURCE VARCHAR(250)

	DECLARE @FORMULA NVARCHAR(MAX), @Pos INT, @Token NVARCHAR(100), @Sign NVARCHAR(1) = '+', @CaseList NVARCHAR(MAX) = '', @InList NVARCHAR(MAX) = ''

	--HoangDM: tinh table 1:
	WHILE EXISTS (SELECT 1 FROM #LIST_BRANCH WHERE INSERTED = 0)
	BEGIN
		SELECT TOP 1 @BRANCH_CODE = BRANCH_CODE 
		FROM #LIST_BRANCH 
		WHERE INSERTED = 0
		ORDER BY BRANCH_CODE
	
		WHILE EXISTS (SELECT 1 FROM #FOMULA WHERE INSERTED = 0 AND ISNULL(FORMULA,'') = '')
		BEGIN
			SELECT TOP 1 @STT = STT, @ITEM_CODE = ITEM_CODE, @ITEM_NAME = ITEM_NAME, @SOURCE_COL = SOURCE_COL
				, @MA_SO = MA_SO, @SOURCE = [SOURCE]
			FROM #FOMULA 
			WHERE INSERTED = 0 AND ISNULL(FORMULA,'') = ''
			ORDER BY STT

			SET @STR_EXEC = ''

			IF @SOURCE = '[MBV_MIS_DB ].APPS.REP_TOI_FINAL_TT'
			BEGIN
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD'')
						, SUM('+CASE WHEN @STT = '5' THEN 'THULAI_KH_A'
									WHEN @STT = '18' THEN 'CHILAI_FTP_B'
									WHEN @STT = '57' THEN 'CHI_DP_F' END +') AS AMOUNT
					FROM ##DATA_TOI
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END
			ELSE IF @SOURCE = '[MBV_MIS_DB ].APPS.MB_AGG_NIM_M'
			BEGIN
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD'')
						, SUM('+CASE WHEN @STT = '8' THEN 'REAL_INTEREST_VND'
									WHEN @STT = '21' THEN 'INTEREST_FTP_VND' END +') AS AMOUNT
					FROM ##DATA_NIM
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END
			ELSE IF @SOURCE = '[MBV_MIS_DB ].APPS.MB_GL_V6_BALANCES'
			BEGIN 
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD''), SUM(CUOIKY_CREDIT-CUOIKY_DEBIT) AS AMOUNT
					FROM #DATA_V6
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END
			ELSE IF @SOURCE = '[MBV_MIS_DB ].[APPS].[MB_STAG_GL_ORS_PL]'
			BEGIN
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD''), SUM(AMOUNT) AS AMOUNT
					FROM #DATA_PL
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+''' AND KPI_CODE IN('''+REPLACE(@SOURCE_COL,',',''',''')+''')
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END

			--if @STT = 31
			--begin
			--	 print @str_exec
			--	-- return
			--end

			EXEC(@STR_EXEC)

			UPDATE #FOMULA 
			SET INSERTED = 1 
			WHERE STT = @STT	

		END
		
		--HoangDM: INSERT cac chi tieu cong thuc
		WHILE EXISTS (SELECT 1 FROM #FOMULA WHERE INSERTED = 0 AND ISNULL(FORMULA,'') <> '')
		BEGIN
			SELECT TOP 1 @STT = STT, @ITEM_CODE = ITEM_CODE, @ITEM_NAME = ITEM_NAME
				, @MA_SO = MA_SO, @SOURCE = SOURCE, @FORMULA = FORMULA
			FROM #FOMULA 
			WHERE INSERTED = 0 AND ISNULL(FORMULA,'') <> ''
		
			SET @Pos = PATINDEX('%[-+]%', @FORMULA);
			SET @Sign = '+';

			-- Xử lý chuỗi
			WHILE LEN(@FORMULA) > 0
			BEGIN
				-- Tìm dấu +/- tiếp theo
				SET @Pos = PATINDEX('%[-+]%', @FORMULA);

				IF @Pos = 0
				BEGIN
					SET @Token = LTRIM(RTRIM(@FORMULA));
					SET @FORMULA = '';
				END
				ELSE
				BEGIN
					SET @Token = LTRIM(RTRIM(LEFT(@FORMULA, @Pos - 1)));
				END

				-- Xử lý token với dấu hiện tại
				IF LEN(@Token) > 0
				BEGIN
					IF @Sign = '+'
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN AMOUNT ';
					ELSE
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN -AMOUNT ';

					SET @InList = @InList + '''' + @Token + ''',';
				END

				-- Cập nhật dấu cho token tiếp theo
				IF @Pos > 0
					SET @Sign = SUBSTRING(@FORMULA, @Pos, 1);

				IF @Pos > 0
					SET @FORMULA = SUBSTRING(@FORMULA, @Pos + 1, LEN(@FORMULA));
			END;
		
			SET @InList = LEFT(@InList, LEN(@InList) - 1);

			IF @SOURCE = '[MBV_MIS_DB ].[APPS].[MB_STAG_GL_ORS_PL]'
			BEGIN 
				SET @STR_EXEC = 
				'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
							, ISNULL(DIVISION_CODE,''KXD''),  SUM(CASE ' + REPLACE(@CaseList,'MA_SO','KPI_CODE') + 'END)
					FROM #DATA_PL
					WHERE KPI_CODE IN (' + @InList + ') AND BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				';
			END
			ELSE IF @SOURCE = 'RESUL_PL_KHOI_QT'
			BEGIN
				SET @STR_EXEC = 
				'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
							, ISNULL(DIVISION_CODE,''KXD''),  SUM(CASE ' + @CaseList + 'END)
					FROM #RAW_DATA
					WHERE MA_SO IN (' + @InList + ') AND BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				';
			END

			EXEC(@STR_EXEC)

			UPDATE #FOMULA 
			SET INSERTED = 1 
			WHERE STT = @STT

			SET @CaseList = ''
			SET @InList = ''
		END

		UPDATE #LIST_BRANCH 
		SET INSERTED = 1
		WHERE BRANCH_CODE = @BRANCH_CODE
		
		UPDATE #FOMULA 
		SET INSERTED = 0 
		WHERE INSERTED = 1
		
	END

	--HoangDM: Insert nhung chi tieu = 0
	UPDATE #LIST_BRANCH SET INSERTED = 0

	WHILE EXISTS (SELECT * FROM #LIST_BRANCH WHERE INSERTED = 0)
	BEGIN
		SELECT TOP 1 @BRANCH_CODE = BRANCH_CODE 
		FROM #LIST_BRANCH WHERE INSERTED = 0

		INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
		SELECT T1.STT, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO, @BRANCH_CODE,'INDIV', 0
		FROM #FOMULA T1
			LEFT JOIN #RAW_DATA T2 ON T1.MA_SO = T2.MA_SO AND T2.BRANCH_CODE = @BRANCH_CODE
		WHERE T2.MA_SO IS NULL

		UPDATE #LIST_BRANCH
		SET INSERTED = 1
		WHERE BRANCH_CODE = @BRANCH_CODE
	END

	UPDATE #RAW_DATA
	SET DIVISION_CODE = 'KXD' WHERE DIVISION_CODE = 'NULL'

	DROP TABLE IF EXISTS #RAW_DATA_T2 --Data table 2:

	--Lay cac chi tieu gia tri = table 1:
	SELECT T1.STT, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO, T1.BRANCH_CODE, T1.DIVISION_CODE, T1.AMOUNT
	INTO #RAW_DATA_T2
	FROM #RAW_DATA T1 
		LEFT JOIN #FOMULA T2 ON T1.STT = T2.STT
	WHERE T2.FORMULA_T2 = 'TU_THAN'

	--Lay cac chi tieu gia tri = 0: 
	INSERT INTO #RAW_DATA_T2
	SELECT T1.STT, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO, T1.BRANCH_CODE, T1.DIVISION_CODE, 0 AS AMOUNT
	FROM #RAW_DATA T1 
		LEFT JOIN #FOMULA T2 ON T1.STT = T2.STT
	WHERE T2.FORMULA_T2 = '0'

	UPDATE #FOMULA SET INSERTED = 0 
	UPDATE #LIST_BRANCH SET INSERTED = 0 
	
	DECLARE @FORMULA_T2 VARCHAR(500)


	--HoangDM: Insert cac chi tieu cong thuc Table 2:
	WHILE EXISTS (SELECT 1 FROM #LIST_BRANCH WHERE INSERTED = 0)
	BEGIN
		SELECT TOP 1 @BRANCH_CODE = BRANCH_CODE 
		FROM #LIST_BRANCH 
		WHERE INSERTED = 0
		ORDER BY BRANCH_CODE
		
		SET @STR_EXEC = ''

		WHILE EXISTS (SELECT 1 FROM #FOMULA WHERE INSERTED = 0 AND FORMULA_T2 <> 'TU_THAN' AND FORMULA_T2 <> '0' AND BAC IS NOT NULL)
		BEGIN
			SELECT TOP 1 @STT = STT, @ITEM_CODE = ITEM_CODE, @ITEM_NAME = ITEM_NAME
				, @MA_SO = MA_SO, @FORMULA_T2 = FORMULA_T2
			FROM #FOMULA 
			WHERE INSERTED = 0 AND FORMULA_T2 <> 'TU_THAN' AND FORMULA_T2 <> '0' AND BAC IS NOT NULL
			ORDER BY BAC DESC

			SET @Pos = PATINDEX('%[-+]%', @FORMULA_T2);
			SET @Sign = '+'

			-- Xử lý chuỗi
			WHILE LEN(@FORMULA_T2) > 0
			BEGIN
				-- Tìm dấu +/- tiếp theo
				SET @Pos = PATINDEX('%[-+]%', @FORMULA_T2);

				IF @Pos = 0
				BEGIN
					SET @Token = LTRIM(RTRIM(@FORMULA_T2));
					SET @FORMULA_T2 = '';
				END
				ELSE
				BEGIN
					SET @Token = LTRIM(RTRIM(LEFT(@FORMULA_T2, @Pos - 1)));
				END

				-- Xử lý token với dấu hiện tại
				IF LEN(@Token) > 0
				BEGIN
					IF @Sign = '+'
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN AMOUNT ';
					ELSE
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN -AMOUNT ';

					SET @InList = @InList + '''' + @Token + ''',';
				END

				-- Cập nhật dấu cho token tiếp theo
				IF @Pos > 0
					SET @Sign = SUBSTRING(@FORMULA_T2, @Pos, 1);

				IF @Pos > 0
					SET @FORMULA_T2 = SUBSTRING(@FORMULA_T2, @Pos + 1, LEN(@FORMULA_T2));
			END;
		
			SET @InList = LEFT(@InList, LEN(@InList) - 1);
			SET @STR_EXEC = 
			'
				INSERT INTO #RAW_DATA_T2 (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
				SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD''),  SUM(CASE ' + @CaseList + 'END)
				FROM #RAW_DATA_T2
				WHERE MA_SO IN (' + @InList + ') AND BRANCH_CODE = '''+@BRANCH_CODE+'''
				GROUP BY BRANCH_CODE, DIVISION_CODE
				';
		


			EXEC(@STR_EXEC)

			UPDATE #FOMULA 
			SET INSERTED = 1 
			WHERE STT = @STT

			SET @CaseList = ''
			SET @InList = ''
		END

		UPDATE #LIST_BRANCH 
		SET INSERTED = 1
		WHERE BRANCH_CODE = @BRANCH_CODE
		
		UPDATE #FOMULA 
		SET INSERTED = 0 
		WHERE INSERTED = 1
	END

	------------------------------------------------------------------------------------------------------------------
	DECLARE @LIST VARCHAR(MAX) = '',@ISNULL_LIST VARCHAR(MAX) = '', @TOTAL VARCHAR(MAX)

	--SELECT @LIST = @LIST + ',[' + DIVISION_CODE + ']'
	--FROM (SELECT DISTINCT DIVISION_CODE FROM #RAW_DATA) AS t;

	--SET @LIST = STUFF(@LIST, 1, 1, '');

	SET @LIST = 'TREASURY, INDIV, FI, CIB, SMEs, DVC, INVEST, KXD, ALM, NHS'
	SET @ISNULL_LIST = 'ISNULL(TREASURY,0) AS TREASURY, ISNULL(INDIV,0) AS INDIV,
		ISNULL(FI,0) AS FI, ISNULL(CIB,0) AS CIB,ISNULL(SMEs,0) AS SMEs, ISNULL(DVC,0) AS DVC,
		ISNULL(INVEST,0) AS INVEST, ISNULL(KXD,0) AS KXD, ISNULL(ALM,0) AS ALM, ISNULL(NHS,0) AS NHS'

	SET @TOTAL = 'ISNULL(TREASURY,0) + ISNULL(INDIV,0) + ISNULL(FI,0) + ISNULL(CIB,0) + ISNULL(SMEs,0) + ISNULL(DVC,0) + ISNULL(INVEST,0)  + ISNULL(KXD,0)  + ISNULL(ALM,0) + ISNULL(NHS,0)'

	------------------------------------------------------------------------------------------------------------------
	DELETE FROM RESUL_PL_KHOI_QT
	WHERE TXN_DATE = @TDATE

	SET @STR_EXEC = 
	'
		INSERT INTO RESUL_PL_KHOI_QT
		(
			TXN_DATE, [TABLE], STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, TOTAL, TREASURY, INDIV, FI, CIB, SMEs, DVC, INVEST, KXD, ALM, NHS,
			CREATED_AT, TDATE
		)
		SELECT '''+CAST(@TDATE AS VARCHAR(15))+''', ''1'', STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO,'+@TOTAL+' AS Total,'+@ISNULL_LIST+',GETDATE()
			, '''+CAST(@TDATE AS VARCHAR(10))+'''
		FROM 
		(
			SELECT STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, DIVISION_CODE, AMOUNT
			FROM #RAW_DATA
		) AS src
		PIVOT (
			SUM(AMOUNT)
			FOR DIVISION_CODE IN ('+@LIST+')
		) AS pvt
		ORDER BY BRANCH_CODE, STT
	'
	EXEC(@STR_EXEC)
	
	SET @STR_EXEC = 
	'
		INSERT INTO RESUL_PL_KHOI_QT
		(
			TXN_DATE, [TABLE], STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, TOTAL, TREASURY, INDIV, FI, CIB, SMEs, DVC, INVEST, KXD, ALM, NHS,
			CREATED_AT, TDATE
		)
		SELECT '''+CAST(@TDATE AS VARCHAR(15))+''',''2'', STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO,'+@TOTAL+' AS Total,'+@ISNULL_LIST+',GETDATE()
			,'''+CAST(@TDATE AS VARCHAR(10))+'''
		FROM 
		(
			SELECT STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, DIVISION_CODE, AMOUNT
			FROM #RAW_DATA_T2
		) AS src
		PIVOT (
			SUM(AMOUNT)
			FOR DIVISION_CODE IN ('+@LIST+')
		) AS pvt
		ORDER BY BRANCH_CODE, STT
	'
	EXEC(@STR_EXEC)

	;WITH TEMP AS 
	(
		SELECT * 
		FROM MIS_DEV.dbo.RESUL_PL_KHOI_QT  
		WHERE [TABLE] = '2' AND TXN_DATE = @TDATE
	)
	SELECT T1.BRANCH_CODE, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO,
		T1.TOTAL, T1.TREASURY, T1.INDIV, T1.FI, T1.CIB, T1.SMEs, T1.DVC, T1.INVEST, T1.KXD, T1.ALM, T1.NHS,
		T2.TOTAL, T2.TREASURY, T2.INDIV, T2.FI, T2.CIB, T2.SMEs, T2.DVC, T2.INVEST, T2.KXD, T2.ALM, T2.NHS
	FROM MIS_DEV.dbo.RESUL_PL_KHOI_QT T1 
		LEFT JOIN TEMP T2 ON T1.BRANCH_CODE = T2.BRANCH_CODE AND T1.MA_SO = T2.MA_SO
	WHERE T1.[TABLE] = '1' AND T1.TXN_DATE = @TDATE
	ORDER BY T1.BRANCH_CODE, T1.STT

	DROP TABLE IF EXISTS ##DATA_NIM
	DROP TABLE IF EXISTS #DATA_PL
	DROP TABLE IF EXISTS ##DATA_TOI
	DROP TABLE IF EXISTS #DATA_V6
	DROP TABLE IF EXISTS #FOMULA
	DROP TABLE IF EXISTS #LIST_BRANCH
	DROP TABLE IF EXISTS #RAW_DATA

END


