/*Problem:
Calculate P&L (Profit & Loss) metrics for each business unit. The metrics are defined in the MAP_PL_QUAN_TRI_FORMULA table, including metric code, metric name, and calculation logic.

Solution:
A looping stored procedure was implemented to calculate each metric by business unit and insert the results into the RESULT_PL_KHOI_QT table.
*/

USE [MIS_DEV]
GO
/****** Object:  StoredProcedure [dbo].[SP_REPORT_PL_KHOI_QT]    Script Date: 9/23/2025 11:53:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_REPORT_PL_KHOI_QT]
	--@FDATE DATE = NULL, --Tu ngay
	@TDATE DATE = '2025-07-27' --Den ngay
AS
BEGIN
	SET NOCOUNT ON

	--DECLARE @TDATE_TT DATE --Ngay cuoi thang truoc
	--SET @TDATE_TT = DATEADD(DAY, -DAY(@TDATE),@TDATE)

	--IF @FDATE IS NULL 
	--	SET @FDATE = FORMAT(@TDATE,'yyyy-01-01')

	DECLARE @STR_EXEC NVARCHAR(MAX) = ''

	DROP TABLE IF EXISTS #LIST_BRANCH

	SELECT DISTINCT 'VN0010' + BRANCH_CODE AS BRANCH_CODE, CAST(0 AS INT) AS INSERTED
	INTO #LIST_BRANCH
	FROM [MIS_DB ].[APPS].[STAG_GL_ORS_PL] WHERE REPORT_DATE = @TDATE

	--delete from #LIST_BRANCH
	--where BRANCH_CODE <> 'vn0010001'
	------------------------------------------------------------------------------------------------------------------
	DROP TABLE IF EXISTS #FOMULA 

	SELECT *, CAST(0 AS INT) AS INSERTED 
	INTO #FOMULA
	FROM MIS_DEV.DBO.MAP_PL_QUAN_TRI_FOMULA
	------------------------------------------------------------------------------------------------------------------
	DROP TABLE IF EXISTS #DATA_PL 

	--HoangDM: So phat sinh tu FDate toi TDate
	SELECT 'VN0010' + BRANCH_CODE AS BRANCH_CODE, KPI_CODE, DIVISION_CODE, 
		SUM(AMOUNT) AS AMOUNT
	INTO #DATA_PL
	FROM [MIS_DB ].[APPS].[STAG_GL_ORS_PL]
	WHERE REPORT_DATE = @TDATE 
	GROUP BY BRANCH_CODE, KPI_CODE, DIVISION_CODE
	
	UPDATE #DATA_PL
	SET DIVISION_CODE = 'TREASURY'
	WHERE DIVISION_CODE = 'TREA'

	UPDATE #DATA_PL
	SET DIVISION_CODE = 'KXD'
	WHERE DIVISION_CODE IN ('KHOI KD-KXD', N'KHÁC', 'KHOI_KD_KXD') OR DIVISION_CODE IS NULL 

	UPDATE #DATA_PL 
	SET DIVISION_CODE = 'NHS'
	WHERE DIVISION_CODE = 'COST CENTER' OR DIVISION_CODE ='?COST CENTER?'

	UPDATE #DATA_PL
	SET DIVISION_CODE = 'SMEs' 
	WHERE DIVISION_CODE IN ('SME','?SMEs?')

	CREATE NONCLUSTERED INDEX BRANCH_CODE ON #DATA_PL (BRANCH_CODE);
	CREATE NONCLUSTERED INDEX KPI_CODE ON #DATA_PL (KPI_CODE);
	------------------------------------------------------------------------------------------------------------------
	--TOI DATA:
	DROP TABLE IF EXISTS ##DATA_TOI

	--SELECT T.MA_CN AS BRANCH_CODE, T.KHOI AS DIVISION_CODE,
	--	SUM(T.THULAI_KH_A) AS THULAI_KH_A, SUM(CHILAI_FTP_B) AS CHILAI_FTP_B, SUM(T.CHI_DP_F) AS CHI_DP_F 
	--INTO ##DATA_TOI
	--FROM [MIS_DB ].[APPS].[REP_TOI_FINAL_MONTH_LK] T
	--	INNER JOIN MASTER_DATA.DBO.DIM_BAD_BOOK V on T.MAKH = V.T24_CUSTOMER_ID and [Phân loại] != 'No tiem an'
	--WHERE TRANSACTION_DATE = @TDATE_TT AND T.KHOI IN('INDIV','SME','CIB','FI')
	--GROUP BY T.MA_CN, T.KHOI	

	--HoangDM: Lay truc tiep Data TOI tu FTP 
	SET @STR_EXEC = N'
		SELECT TRIM(T.MA_CN) AS BRANCH_CODE, T.KHOI AS DIVISION_CODE,
				SUM(T.THULAI_KH_A) AS THULAI_KH_A, 
				SUM(T.CHILAI_FTP_B) AS CHILAI_FTP_B, 
				SUM(T.CHI_DP_F) AS CHI_DP_F 
		INTO ##DATA_TOI
		FROM OPENQUERY(ftp1_linked, 
			''SELECT MA_CN, KHOI, THULAI_KH_A, CHILAI_FTP_B, CHI_DP_F, MAKH 
				FROM APPS.REP_TOI_FINAL_TT
				WHERE TRANSACTION_DATE BETWEEN ''''2025-02-07'''' AND ''''' + CAST(@TDATE AS VARCHAR(10)) + N''''' 
				AND TRIM(KHOI) IN (''''INDIV'''',''''SME'''',''''CIB'''',''''FI'''')''
		) T
			INNER JOIN MASTER_DATA.DBO.DIM_BAD_BOOK V ON T.MAKH = V.T24_CUSTOMER_ID 
				AND V.[Phân loại] != ''No tiem an''
		GROUP BY TRIM(T.MA_CN), T.KHOI;
		'
	EXEC (@STR_EXEC)

	UPDATE ##DATA_TOI
	SET DIVISION_CODE = 'SMEs'
	WHERE DIVISION_CODE = 'SME'
	------------------------------------------------------------------------------------------------------------------
	--NIM DATA
	DROP TABLE IF EXISTS ##DATA_NIM
	--SELECT T1.CN AS BRANCH_CODE, T1.KHOI AS DIVISION_CODE,
	--	SUM(REAL_INTEREST_VND) AS REAL_INTEREST_VND, SUM(INTEREST_FTP_VND) AS INTEREST_FTP_VND
	--INTO ##DATA_NIM
	--FROM ftp1_linked..APPS.AGG_NIM_M T1
	--	INNER JOIN MASTER_DATA.DBO.DIM_PVI_SBIC T2 ON T1.TAIKHOAN = T2.ARRANGEMENT_NBR AND T2.PVN_SBIC = 'PVN_SBIC'
	--WHERE KHOI IN ('INDIV','SME','CIB','FI') AND D_TYPE = 'DEPOSIT'
	--	AND TRANSACTION_DATE = @TDATE_TT 
	--GROUP BY T1.CN, T1.KHOI

	--HoangDM: Lay truc tiep Data NIM tu FTP 
	SET @STR_EXEC = '
		SELECT T1.CN AS BRANCH_CODE,  T1.KHOI AS DIVISION_CODE,
			   SUM(REAL_INTEREST_VND) AS REAL_INTEREST_VND, 
			   SUM(INTEREST_FTP_VND) AS INTEREST_FTP_VND
		INTO ##DATA_NIM
		FROM OPENQUERY(ftp1_linked, 
			''SELECT CN, KHOI, REAL_INTEREST_VND, INTEREST_FTP_VND, TAIKHOAN 
			  FROM APPS.AGG_NIM_M 
			  WHERE D_TYPE = ''''DEPOSIT'''' 
				AND TRANSACTION_DATE BETWEEN ''''2025-02-07'''' AND ''''' + CAST(@TDATE AS varchar(10)) + '''''
				AND TRIM(KHOI) IN (''''INDIV'''',''''SME'''',''''CIB'''',''''FI'''')''
		) T1
			INNER JOIN MASTER_DATA.DBO.DIM_PVI_SBIC T2 ON T1.TAIKHOAN = T2.ARRANGEMENT_NBR 
				AND T2.PVN_SBIC = ''PVN_SBIC''
		GROUP BY T1.CN, T1.KHOI;
		'		
	EXEC (@STR_EXEC);

	UPDATE ##DATA_NIM
	SET DIVISION_CODE = 'SMEs'
	WHERE DIVISION_CODE = 'SME'
	------------------------------------------------------------------------------------------------------------------
	--V6 DATA
	DROP TABLE IF EXISTS #DATA_V6
	SELECT CNC1 AS BRANCH_CODE, 
		CASE WHEN LINE_GL = '704000' THEN 'SMEs'
			WHEN LINE_GL = '704100' THEN 'INDIV'
			WHEN LINE_GL = '703900' THEN 'CIB' END AS DIVISION_CODE,
		SUM(CUOIKY_CREDIT) AS CUOIKY_CREDIT ,
		SUM(CUOIKY_DEBIT) AS CUOIKY_DEBIT 
	INTO #DATA_V6
	FROM [MIS_DB ].APPS.GL_V6_BALANCES
	WHERE TRANSACTION_DATE = @TDATE AND LINE_GL IN ('704000','704100','703900')
	GROUP BY CNC1, LINE_GL
	------------------------------------------------------------------------------------------------------------------
	DROP TABLE IF EXISTS #RAW_DATA

	CREATE TABLE #RAW_DATA
	(
		STT INT,
		ITEM_CODE VARCHAR(100),
		ITEM_NAME NVARCHAR(250),
		MA_SO VARCHAR(15),
		BRANCH_CODE VARCHAR(15),
		DIVISION_CODE VARCHAR(15),
		AMOUNT NUMERIC(38,4)
	)


	--HoangDM: import tay TOI truoc 7/2:
	DROP TABLE IF EXISTS #TEMP 
	CREATE TABLE #TEMP	 
	(
		BRANCH_CODE NVARCHAR(50),
		ITEM_CODE VARCHAR(50),
		ITEM_NAME NVARCHAR(250),
		MA_SO NVARCHAR(50),
		INDIV NUMERIC(30,0),
		FI NUMERIC(30,0),
		SMEs NUMERIC(30,0)

	)

	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010001', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -23063008932.2512 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010002', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -31.0301369863013 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010003', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 2298686215, -3833905889.4143 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010004', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -13201007.0755677 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010005', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010006', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010007', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010008', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010009', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010010', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010011', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -6005.10223561644 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010012', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010013', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010014', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010017', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010020', 'CHI_LAI_HUY_DONG_KH_PVN_SBIC', N'2.1 Chi lãi huy động KH PVN&SBIC', 'A121' , 0, 0, -466.966575342465 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010202', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 126.290753424657 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010203', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 374.721890410958 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010204', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010205', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 33280990.4094383 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010208', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 126202120.821577 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010221', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010223', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 1150.58767123288 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010231', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010232', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010233', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010252', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010666', 'FTP_KHACH_HANG_PVN_SBIC', N'FTP khách hàng PVN&SBIC', 'A17121' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010001', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -1444548651, 0, -9984639486 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010002', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -67965924, 0, -119056821 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010003', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -28093128, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010004', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -3458598, 0, -429523628 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010005', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -43780438, 0, -2048943 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010006', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010007', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010008', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -5102023, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010009', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -4741979, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010010', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -67536279, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010011', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , 0, 0, -1461386823 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010012', 'FTP_NO_KHOANH', N'FTP nợ khoanh', 'A17112' , -33316062, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010208', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 1325767, 0, -13248 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010221', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -924, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010223', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , -29785, 0, 652483743 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010231', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010232', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 2472510, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010233', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010252', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, -1052082 
	INSERT INTO #TEMP(BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, INDIV, FI, SMEs) SELECT 'VN0010666', 'THU_LAI_TREO_NO_KHOANH', N'1.2 Thu lãi treo nợ khoanh', 'A112' , 0, 0, 0 

	DROP TABLE IF EXISTS #TEMP2
	SELECT *  
	INTO #TEMP2
	FROM MIS_DEV.DBO.MAP_PL_QUAN_TRI_FOMULA
	WHERE STT IN (5,8,18,21,57)

	;WITH CTE AS
	(
	SELECT T2.STT, T1.*
	FROM #TEMP T1
		LEFT JOIN #TEMP2 T2 ON T1.ITEM_CODE = T2.ITEM_CODE
		)
		insert into #RAW_DATA(STT,ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
		SELECT STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, GIA_TRI
		FROM CTE
		UNPIVOT (
			GIA_TRI FOR DIVISION_CODE IN (
				INDIV, SMEs, FI
			)
		) AS UNPVT;


	DECLARE @BRANCH_CODE VARCHAR(15)

	DECLARE @STT INT, @ITEM_CODE VARCHAR(50), @ITEM_NAME NVARCHAR(250), @MA_SO VARCHAR(15), @SOURCE_COL VARCHAR(250)
		, @SOURCE VARCHAR(250)

	DECLARE @FORMULA NVARCHAR(MAX), @Pos INT, @Token NVARCHAR(100), @Sign NVARCHAR(1) = '+', @CaseList NVARCHAR(MAX) = '', @InList NVARCHAR(MAX) = ''

	--HoangDM: tinh table 1:
	WHILE EXISTS (SELECT 1 FROM #LIST_BRANCH WHERE INSERTED = 0)
	BEGIN
		SELECT TOP 1 @BRANCH_CODE = BRANCH_CODE 
		FROM #LIST_BRANCH 
		WHERE INSERTED = 0
		ORDER BY BRANCH_CODE
	
		WHILE EXISTS (SELECT 1 FROM #FOMULA WHERE INSERTED = 0 AND ISNULL(FORMULA,'') = '')
		BEGIN
			SELECT TOP 1 @STT = STT, @ITEM_CODE = ITEM_CODE, @ITEM_NAME = ITEM_NAME, @SOURCE_COL = SOURCE_COL
				, @MA_SO = MA_SO, @SOURCE = [SOURCE]
			FROM #FOMULA 
			WHERE INSERTED = 0 AND ISNULL(FORMULA,'') = ''
			ORDER BY STT

			SET @STR_EXEC = ''

			IF @SOURCE = '[MIS_DB ].APPS.REP_TOI_FINAL_TT'
			BEGIN
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD'')
						, SUM('+CASE WHEN @STT = '5' THEN 'THULAI_KH_A'
									WHEN @STT = '18' THEN 'CHILAI_FTP_B'
									WHEN @STT = '57' THEN 'CHI_DP_F' END +') AS AMOUNT
					FROM ##DATA_TOI
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END
			ELSE IF @SOURCE = '[MIS_DB ].APPS.AGG_NIM_M'
			BEGIN
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD'')
						, SUM('+CASE WHEN @STT = '8' THEN 'REAL_INTEREST_VND'
									WHEN @STT = '21' THEN 'INTEREST_FTP_VND' END +') AS AMOUNT
					FROM ##DATA_NIM
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END
			ELSE IF @SOURCE = '[MIS_DB ].APPS.GL_V6_BALANCES'
			BEGIN 
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD''), SUM(CUOIKY_CREDIT-CUOIKY_DEBIT) AS AMOUNT
					FROM #DATA_V6
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END
			ELSE IF @SOURCE = '[MIS_DB ].[APPS].[STAG_GL_ORS_PL]'
			BEGIN
				SET @STR_EXEC = 
				N'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)

					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD''), SUM(AMOUNT) AS AMOUNT
					FROM #DATA_PL
					WHERE BRANCH_CODE = '''+@BRANCH_CODE+''' AND KPI_CODE IN('''+REPLACE(@SOURCE_COL,',',''',''')+''')
					GROUP BY BRANCH_CODE, DIVISION_CODE
				'
			END

			--if @STT = 31
			--begin
			--	 print @str_exec
			--	-- return
			--end

			EXEC(@STR_EXEC)

			UPDATE #FOMULA 
			SET INSERTED = 1 
			WHERE STT = @STT	

		END
		
		--HoangDM: INSERT cac chi tieu cong thuc
		WHILE EXISTS (SELECT 1 FROM #FOMULA WHERE INSERTED = 0 AND ISNULL(FORMULA,'') <> '')
		BEGIN
			SELECT TOP 1 @STT = STT, @ITEM_CODE = ITEM_CODE, @ITEM_NAME = ITEM_NAME
				, @MA_SO = MA_SO, @SOURCE = SOURCE, @FORMULA = FORMULA
			FROM #FOMULA 
			WHERE INSERTED = 0 AND ISNULL(FORMULA,'') <> ''
		
			SET @Pos = PATINDEX('%[-+]%', @FORMULA);
			SET @Sign = '+';

			-- Xử lý chuỗi
			WHILE LEN(@FORMULA) > 0
			BEGIN
				-- Tìm dấu +/- tiếp theo
				SET @Pos = PATINDEX('%[-+]%', @FORMULA);

				IF @Pos = 0
				BEGIN
					SET @Token = LTRIM(RTRIM(@FORMULA));
					SET @FORMULA = '';
				END
				ELSE
				BEGIN
					SET @Token = LTRIM(RTRIM(LEFT(@FORMULA, @Pos - 1)));
				END

				-- Xử lý token với dấu hiện tại
				IF LEN(@Token) > 0
				BEGIN
					IF @Sign = '+'
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN AMOUNT ';
					ELSE
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN -AMOUNT ';

					SET @InList = @InList + '''' + @Token + ''',';
				END

				-- Cập nhật dấu cho token tiếp theo
				IF @Pos > 0
					SET @Sign = SUBSTRING(@FORMULA, @Pos, 1);

				IF @Pos > 0
					SET @FORMULA = SUBSTRING(@FORMULA, @Pos + 1, LEN(@FORMULA));
			END;
		
			SET @InList = LEFT(@InList, LEN(@InList) - 1);

			IF @SOURCE = '[MIS_DB ].[APPS].[STAG_GL_ORS_PL]'
			BEGIN 
				SET @STR_EXEC = 
				'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
							, ISNULL(DIVISION_CODE,''KXD''),  SUM(CASE ' + REPLACE(@CaseList,'MA_SO','KPI_CODE') + 'END)
					FROM #DATA_PL
					WHERE KPI_CODE IN (' + @InList + ') AND BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				';
			END
			ELSE IF @SOURCE = 'RESUL_PL_KHOI_QT'
			BEGIN
				SET @STR_EXEC = 
				'
					INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
					SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
							, ISNULL(DIVISION_CODE,''KXD''),  SUM(CASE ' + @CaseList + 'END)
					FROM #RAW_DATA
					WHERE MA_SO IN (' + @InList + ') AND BRANCH_CODE = '''+@BRANCH_CODE+'''
					GROUP BY BRANCH_CODE, DIVISION_CODE
				';
			END

			EXEC(@STR_EXEC)

			UPDATE #FOMULA 
			SET INSERTED = 1 
			WHERE STT = @STT

			SET @CaseList = ''
			SET @InList = ''
		END

		UPDATE #LIST_BRANCH 
		SET INSERTED = 1
		WHERE BRANCH_CODE = @BRANCH_CODE
		
		UPDATE #FOMULA 
		SET INSERTED = 0 
		WHERE INSERTED = 1
		
	END

	--HoangDM: Insert nhung chi tieu = 0
	UPDATE #LIST_BRANCH SET INSERTED = 0

	WHILE EXISTS (SELECT * FROM #LIST_BRANCH WHERE INSERTED = 0)
	BEGIN
		SELECT TOP 1 @BRANCH_CODE = BRANCH_CODE 
		FROM #LIST_BRANCH WHERE INSERTED = 0

		INSERT INTO #RAW_DATA (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
		SELECT T1.STT, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO, @BRANCH_CODE,'INDIV', 0
		FROM #FOMULA T1
			LEFT JOIN #RAW_DATA T2 ON T1.MA_SO = T2.MA_SO AND T2.BRANCH_CODE = @BRANCH_CODE
		WHERE T2.MA_SO IS NULL

		UPDATE #LIST_BRANCH
		SET INSERTED = 1
		WHERE BRANCH_CODE = @BRANCH_CODE
	END

	UPDATE #RAW_DATA
	SET DIVISION_CODE = 'KXD' WHERE DIVISION_CODE = 'NULL'

	DROP TABLE IF EXISTS #RAW_DATA_T2 --Data table 2:

	--Lay cac chi tieu gia tri = table 1:
	SELECT T1.STT, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO, T1.BRANCH_CODE, T1.DIVISION_CODE, T1.AMOUNT
	INTO #RAW_DATA_T2
	FROM #RAW_DATA T1 
		LEFT JOIN #FOMULA T2 ON T1.STT = T2.STT
	WHERE T2.FORMULA_T2 = 'TU_THAN'

	--Lay cac chi tieu gia tri = 0: 
	INSERT INTO #RAW_DATA_T2
	SELECT T1.STT, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO, T1.BRANCH_CODE, T1.DIVISION_CODE, 0 AS AMOUNT
	FROM #RAW_DATA T1 
		LEFT JOIN #FOMULA T2 ON T1.STT = T2.STT
	WHERE T2.FORMULA_T2 = '0'

	UPDATE #FOMULA SET INSERTED = 0 
	UPDATE #LIST_BRANCH SET INSERTED = 0 
	
	DECLARE @FORMULA_T2 VARCHAR(500)


	--HoangDM: Insert cac chi tieu cong thuc Table 2:
	WHILE EXISTS (SELECT 1 FROM #LIST_BRANCH WHERE INSERTED = 0)
	BEGIN
		SELECT TOP 1 @BRANCH_CODE = BRANCH_CODE 
		FROM #LIST_BRANCH 
		WHERE INSERTED = 0
		ORDER BY BRANCH_CODE
		
		SET @STR_EXEC = ''

		WHILE EXISTS (SELECT 1 FROM #FOMULA WHERE INSERTED = 0 AND FORMULA_T2 <> 'TU_THAN' AND FORMULA_T2 <> '0' AND BAC IS NOT NULL)
		BEGIN
			SELECT TOP 1 @STT = STT, @ITEM_CODE = ITEM_CODE, @ITEM_NAME = ITEM_NAME
				, @MA_SO = MA_SO, @FORMULA_T2 = FORMULA_T2
			FROM #FOMULA 
			WHERE INSERTED = 0 AND FORMULA_T2 <> 'TU_THAN' AND FORMULA_T2 <> '0' AND BAC IS NOT NULL
			ORDER BY BAC DESC

			SET @Pos = PATINDEX('%[-+]%', @FORMULA_T2);
			SET @Sign = '+'

			-- Xử lý chuỗi
			WHILE LEN(@FORMULA_T2) > 0
			BEGIN
				-- Tìm dấu +/- tiếp theo
				SET @Pos = PATINDEX('%[-+]%', @FORMULA_T2);

				IF @Pos = 0
				BEGIN
					SET @Token = LTRIM(RTRIM(@FORMULA_T2));
					SET @FORMULA_T2 = '';
				END
				ELSE
				BEGIN
					SET @Token = LTRIM(RTRIM(LEFT(@FORMULA_T2, @Pos - 1)));
				END

				-- Xử lý token với dấu hiện tại
				IF LEN(@Token) > 0
				BEGIN
					IF @Sign = '+'
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN AMOUNT ';
					ELSE
						SET @CaseList = @CaseList + CHAR(10) + 'WHEN MA_SO = ''' + @Token + ''' THEN -AMOUNT ';

					SET @InList = @InList + '''' + @Token + ''',';
				END

				-- Cập nhật dấu cho token tiếp theo
				IF @Pos > 0
					SET @Sign = SUBSTRING(@FORMULA_T2, @Pos, 1);

				IF @Pos > 0
					SET @FORMULA_T2 = SUBSTRING(@FORMULA_T2, @Pos + 1, LEN(@FORMULA_T2));
			END;
		
			SET @InList = LEFT(@InList, LEN(@InList) - 1);
			SET @STR_EXEC = 
			'
				INSERT INTO #RAW_DATA_T2 (STT, ITEM_CODE, ITEM_NAME, MA_SO, BRANCH_CODE, DIVISION_CODE, AMOUNT)
				SELECT '+CAST(@STT AS VARCHAR(15))+N', '''+@ITEM_CODE+N''', N'''+@ITEM_NAME+''', '''+@MA_SO+''', BRANCH_CODE AS BRANCH_CODE
						, ISNULL(DIVISION_CODE,''KXD''),  SUM(CASE ' + @CaseList + 'END)
				FROM #RAW_DATA_T2
				WHERE MA_SO IN (' + @InList + ') AND BRANCH_CODE = '''+@BRANCH_CODE+'''
				GROUP BY BRANCH_CODE, DIVISION_CODE
				';
		


			EXEC(@STR_EXEC)

			UPDATE #FOMULA 
			SET INSERTED = 1 
			WHERE STT = @STT

			SET @CaseList = ''
			SET @InList = ''
		END

		UPDATE #LIST_BRANCH 
		SET INSERTED = 1
		WHERE BRANCH_CODE = @BRANCH_CODE
		
		UPDATE #FOMULA 
		SET INSERTED = 0 
		WHERE INSERTED = 1
	END

	------------------------------------------------------------------------------------------------------------------
	DECLARE @LIST VARCHAR(MAX) = '',@ISNULL_LIST VARCHAR(MAX) = '', @TOTAL VARCHAR(MAX)

	--SELECT @LIST = @LIST + ',[' + DIVISION_CODE + ']'
	--FROM (SELECT DISTINCT DIVISION_CODE FROM #RAW_DATA) AS t;

	--SET @LIST = STUFF(@LIST, 1, 1, '');

	SET @LIST = 'TREASURY, INDIV, FI, CIB, SMEs, DVC, INVEST, KXD, ALM, NHS'
	SET @ISNULL_LIST = 'ISNULL(TREASURY,0) AS TREASURY, ISNULL(INDIV,0) AS INDIV,
		ISNULL(FI,0) AS FI, ISNULL(CIB,0) AS CIB,ISNULL(SMEs,0) AS SMEs, ISNULL(DVC,0) AS DVC,
		ISNULL(INVEST,0) AS INVEST, ISNULL(KXD,0) AS KXD, ISNULL(ALM,0) AS ALM, ISNULL(NHS,0) AS NHS'

	SET @TOTAL = 'ISNULL(TREASURY,0) + ISNULL(INDIV,0) + ISNULL(FI,0) + ISNULL(CIB,0) + ISNULL(SMEs,0) + ISNULL(DVC,0) + ISNULL(INVEST,0)  + ISNULL(KXD,0)  + ISNULL(ALM,0) + ISNULL(NHS,0)'

	------------------------------------------------------------------------------------------------------------------
	DELETE FROM RESUL_PL_KHOI_QT
	WHERE TXN_DATE = @TDATE

	SET @STR_EXEC = 
	'
		INSERT INTO RESUL_PL_KHOI_QT
		(
			TXN_DATE, [TABLE], STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, TOTAL, TREASURY, INDIV, FI, CIB, SMEs, DVC, INVEST, KXD, ALM, NHS,
			CREATED_AT, TDATE
		)
		SELECT '''+CAST(@TDATE AS VARCHAR(15))+''', ''1'', STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO,'+@TOTAL+' AS Total,'+@ISNULL_LIST+',GETDATE()
			, '''+CAST(@TDATE AS VARCHAR(10))+'''
		FROM 
		(
			SELECT STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, DIVISION_CODE, AMOUNT
			FROM #RAW_DATA
		) AS src
		PIVOT (
			SUM(AMOUNT)
			FOR DIVISION_CODE IN ('+@LIST+')
		) AS pvt
		ORDER BY BRANCH_CODE, STT
	'
	EXEC(@STR_EXEC)
	
	SET @STR_EXEC = 
	'
		INSERT INTO RESUL_PL_KHOI_QT
		(
			TXN_DATE, [TABLE], STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, TOTAL, TREASURY, INDIV, FI, CIB, SMEs, DVC, INVEST, KXD, ALM, NHS,
			CREATED_AT, TDATE
		)
		SELECT '''+CAST(@TDATE AS VARCHAR(15))+''',''2'', STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO,'+@TOTAL+' AS Total,'+@ISNULL_LIST+',GETDATE()
			,'''+CAST(@TDATE AS VARCHAR(10))+'''
		FROM 
		(
			SELECT STT, BRANCH_CODE, ITEM_CODE, ITEM_NAME, MA_SO, DIVISION_CODE, AMOUNT
			FROM #RAW_DATA_T2
		) AS src
		PIVOT (
			SUM(AMOUNT)
			FOR DIVISION_CODE IN ('+@LIST+')
		) AS pvt
		ORDER BY BRANCH_CODE, STT
	'
	EXEC(@STR_EXEC)

	;WITH TEMP AS 
	(
		SELECT * 
		FROM MIS_DEV.dbo.RESUL_PL_KHOI_QT  
		WHERE [TABLE] = '2' AND TXN_DATE = @TDATE
	)
	SELECT T1.BRANCH_CODE, T1.ITEM_CODE, T1.ITEM_NAME, T1.MA_SO,
		T1.TOTAL, T1.TREASURY, T1.INDIV, T1.FI, T1.CIB, T1.SMEs, T1.DVC, T1.INVEST, T1.KXD, T1.ALM, T1.NHS,
		T2.TOTAL, T2.TREASURY, T2.INDIV, T2.FI, T2.CIB, T2.SMEs, T2.DVC, T2.INVEST, T2.KXD, T2.ALM, T2.NHS
	FROM MIS_DEV.dbo.RESUL_PL_KHOI_QT T1 
		LEFT JOIN TEMP T2 ON T1.BRANCH_CODE = T2.BRANCH_CODE AND T1.MA_SO = T2.MA_SO
	WHERE T1.[TABLE] = '1' AND T1.TXN_DATE = @TDATE
	ORDER BY T1.BRANCH_CODE, T1.STT

	DROP TABLE IF EXISTS ##DATA_NIM
	DROP TABLE IF EXISTS #DATA_PL
	DROP TABLE IF EXISTS ##DATA_TOI
	DROP TABLE IF EXISTS #DATA_V6
	DROP TABLE IF EXISTS #FOMULA
	DROP TABLE IF EXISTS #LIST_BRANCH
	DROP TABLE IF EXISTS #RAW_DATA

END
